### ISSUE TITLE
webhook variables are not populating under docs.

### ISSUE THREAD

**Issue by joseuo94** [calcom/docs#57]
![Captura de pantalla 2024-05-02 093855](https://github.com/calcom/docs/assets/59074681/7de08903-dd33-40de-a4c6-cc6b9c84d105)

**Comment by alishaz-polymath** [comment]
I think PR #52 broke this. 
cc: @Ryukemeister @supalarry

**Comment by alishaz-polymath** [comment]
Should probably rename `components/components/table.tsx` component because it looks like it is conflicting with the built-in markdoc `table` table.
