### ISSUE TITLE
How to disable confirmation email for attendees 

### ISSUE THREAD

**Issue by milospuac** [calcom/docs#69]
# How to disable confirmation email for attendees

Users who wish to disable booking confirmation emails sent from Cal.com to attendees can do so provided they have a workflow enabled to send an email to attendees upon booking for that specific event type. Follow the steps below to disable confirmation emails:

- **Create a workflow for that event:** Users must have a workflow enabled that sends an email to attendees upon booking for the specific event type. This workflow serves as an alternative method of confirmation. Make sure you select the correct event type for that workflow.

![brandbird (7).png](How%20to%20disable%20confirmation%20email%20for%20attendees%20d5485f5526534039b9419add17eb5c4b/brandbird_(7).png)

**Steps to Disable Confirmation Email:**

1. **Access Event Settings:** Navigate to the advanced settings of the event type for which you wish to disable confirmation emails. 

![brandbird (8).png](How%20to%20disable%20confirmation%20email%20for%20attendees%20d5485f5526534039b9419add17eb5c4b/brandbird_(8).png)

1. **Toggle Confirmation Email Setting:** Within the advanced settings of the event type, locate the option labeled `Disable default confirmation emails for attendees` at the very bottom. Toggle this option to disable confirmation emails for attendees. 

![brandbird (6).png](How%20to%20disable%20confirmation%20email%20for%20attendees%20d5485f5526534039b9419add17eb5c4b/brandbird_(6).png)

1. **Save Changes:** After disabling confirmation emails, remember to save your changes to ensure they take effect.

**Comment by alishaz-polymath** [comment]
Again, the images seems broken here. Can you add them in comments maybe? @milospuac

**Comment by milospuac** [comment]
![brandbird (7)](https://github.com/calcom/docs/assets/97884287/6d76df8f-075a-4331-9aca-d770866137d2)

**Comment by milospuac** [comment]
![brandbird (8)](https://github.com/calcom/docs/assets/97884287/12ee5739-6809-443e-888e-88cb3a035f84)

**Comment by milospuac** [comment]
![brandbird (6)](https://github.com/calcom/docs/assets/97884287/7f68063d-a939-4361-81cd-73cf0a0cb219)
